# Generated by Django 4.0.3 on 2022-03-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fishgrid_app', '0003_categ_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_reg',
            name='con_password',
        ),
        migrations.AddField(
            model_name='customer_reg',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopregistration',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopregistration',
            name='phonenumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
