# Generated by Django 3.0.5 on 2022-03-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fishgrid_app', '0005_alter_product_category_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fishgrid_app.shopRegistration'),
        ),
    ]
