# Generated by Django 3.0.5 on 2022-03-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fishgrid_app', '0006_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catg_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fishgrid_app.Categ'),
        ),
    ]
