# Generated by Django 3.0.5 on 2022-03-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fishgrid_app', '0007_product_catg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catg_id',
            new_name='catg',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
