# Generated by Django 3.0.5 on 2022-03-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fishgrid_app', '0015_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
