# Generated by Django 3.0.5 on 2022-03-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fishgrid_app', '0018_auto_20220324_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fishgrid_app.shopRegistration'),
        ),
    ]
