# Generated by Django 3.0.5 on 2022-03-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fishgrid_app', '0019_feedback_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fishgrid_app.shopRegistration'),
        ),
    ]
