# Generated by Django 4.0.3 on 2022-04-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fishgrid_app', '0021_customer_reg_con_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopregistration',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
