# Generated by Django 4.0.3 on 2022-04-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fishgrid_app', '0022_shopregistration_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='directpay',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
