# Generated by Django 3.0.5 on 2022-04-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fishgrid_app', '0025_auto_20220430_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='directpay',
        ),
    ]
